name: Lerna Publish

on:
  push:
    branches:
      - main

jobs:
  lerna_publish:
    name: Lerna Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Publish changed packages
        run: npx lerna publish minor --yes
