name: Lerna Publish

on:
  push:
    branches:
      - main

jobs:
  lerna_publish:
    name: Lerna Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: gitconfig
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"


      - name: Publish changed packages
        run: npx lerna publish minor --yes
