name: Lerna Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - 'r**'

jobs:
  lerna_publish:
    if: ${{ github.event.pull_request.merged == true }}
    name: Lerna Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5000
          token: ${{ secrets.PAT_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: gitconfig
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

#      - name: Cache node modules
#        id: cache-npm
#        uses: actions/cache@v3
#
#        env:
#          cache-name: cache-node-modules
#        with:
#          # npm cache files are stored in `~/.npm` on Linux/macOS
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
#        name: List the state of node modules
#        continue-on-error: true
#        run: npm list

      - name: Install dependencies
        run: npm install --no-save

      - name: Publish changed packages
        run: npx lerna publish minor --yes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
