name: Lerna Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - 'r**'

jobs:
  lerna_publish:
    if: ${{ github.event.pull_request.merged == true }}
    name: Lerna Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5000
          token: ${{ secrets.PAT_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: Get app versions
        run: |
          versions=()
          for folder in apps/*; do
            if [ -f "$folder/package.json" ]; then
              version=$(jq -r '.version' "$folder/package.json")
              versions+=("$folder:$version")
            fi
          done
          echo "::set-output name=app_versions::${versions[*]}"
        id: get_versions

      - name: gitconfig
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install --no-save

      - name: Publish changed packages
        run: npx lerna publish minor --yes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update package versions if necessary
        run: |
          versions="${{ steps.get_versions.outputs.app_versions }}"
          IFS=' ' read -r -a array <<< "$versions"
          for element in "${array[@]}"
          do
            folder=$(echo "$element" | cut -d':' -f1)
            version=$(echo "$element" | cut -d':' -f2)
            if [[ $version == *"-alpha"* ]]; then
              version=${version%%-alpha*}
              version=${version%?}0
              jq ".version = \"${version}\"" "$folder/package.json" > "$folder/package.tmp" && mv "$folder/package.tmp" "$folder/package.json"
            fi
          done

      - name: Commit and push changes
        run: |
          git add apps/*/package.json
          git commit -m "Auto-update package versions" --all
          git push
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
