name: Lerna Publish

on:
  push:
    branches:
      - main

jobs:
  lerna_publish:
    name: Lerna Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: gitconfig
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm install

      - name: Commit changes
        uses: EndBug/add-and-commit@v2.1.0
        with: # More info about the arguments on the action page
          author_name: Displayed name
          author_email: Displayed email
          message: "Message for the commit"
          path: local/path/to/built/version
          pattern: "*.js" # Pattern that matches the files to commit
          force: true # Whether to use the --force flag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically

      - name: Publish changed packages
        run: npx lerna publish minor --yes
