name: Update Package Versions

on:
  push:
    branches:
      - fre

jobs:
  update_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get app versions
        run: |
          versions=()
          for folder in apps/*; do
            if [ -f "$folder/package.json" ]; then
              version=$(jq -r '.version' "$folder/package.json")
              versions+=("$folder:$version")
            fi
          done
          echo "::set-output name=app_versions::${versions[*]}"
        id: get_versions

      - name: Update package versions if necessary
        run: |
          versions="${{ steps.get_versions.outputs.app_versions }}"
          IFS=' ' read -r -a array <<< "$versions"
          for element in "${array[@]}"
          do
            folder=$(echo "$element" | cut -d':' -f1)
            version=$(echo "$element" | cut -d':' -f2)
            if [[ $version == *"-alpha"* ]]; then
              version=${version%%-alpha*}
              version=${version%?}0
              jq ".version = \"${version}\"" "$folder/package.json" > "$folder/package.tmp" && mv "$folder/package.tmp" "$folder/package.json"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add apps/*/package.json
          git commit -m "Auto-update package versions" --all
          git push