name: Lerna Publish

on:
  push:
    branches:
      - fre
jobs:

    get_versions:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install dependencies
          run: npm install

        - name: Get app versions
          id: get_versions
          run: |
            versions=()
            for folder in apps/*; do
              if [ -f "$folder/package.json" ]; then
                version=$(jq -r '.version' "$folder/package.json")
                versions+=("$folder:$version")
              fi
            done
            echo "::set-output name=app_versions::${versions[@]}"

        - name: Save app versions to file
          run: echo "${{ steps.get_versions.outputs.app_versions }}" > app_versions.txt
